export const GET_ALL_ORDERS_ADMIN_REQUEST = "GET_ALL_ORDERS_ADMIN_REQUEST";
export const GET_ALL_ORDERS_ADMIN_SUCCESS = "GET_ALL_ORDERS_ADMIN_SUCCESS";
export const GET_ALL_ORDERS_ADMIN_FAIL = "GET_ALL_ORDERS_ADMIN_FAIL";

export const GET_ORDER_ADMIN_REQUEST = "GET_ORDER_ADMIN_REQUEST";
export const GET_ORDER_ADMIN_SUCCESS = "GET_ORDER_ADMIN_SUCCESS";
export const GET_ORDER_ADMIN_FAIL = "GET_ORDER_ADMIN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
