export const CHECK_RENTAL_REQUEST = "CHECK_RENTAL_REQUEST";
export const CHECK_RENTAL_SUCCESS = "CHECK_RENTAL_SUCCESS";
export const CHECK_RENTAL_FAIL = "CHECK_RENTAL_FAIL";
export const CHECK_RENTAL_RESET = "CHECK_RENTAL_RESET";

export const CALENDAR_AVAILABILITY_SUCCESS = "CALENDAR_AVAILABILITY_SUCCESS";
export const CALENDAR_AVAILABILITY_FAIL = "CALENDAR_AVAILABILITY_FAIL";

export const USER_RENTALS_SUCCESS = "USER_RENTALS_SUCCESS";
export const USER_RENTALS_FAIL = "USER_RENTALS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
