export const ALL_TENTS_SUCCESS = "ALL_TENTS_SUCCESS";
export const ALL_TENTS_FAIL = "ALL_TENTS_FAIL";

export const TENTS_DETAILS_REQUEST = "TENTS_DETAILS_REQUEST";
export const TENTS_DETAILS_SUCCESS = "TENTS_DETAILS_SUCCESS";
export const TENTS_DETAILS_FAIL = "TENTS_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
