export const ALL_TENTS_SUCCESS = "ALL_TENTS_SUCCESS";
export const ALL_TENTS_FAIL = "ALL_TENTS_FAIL";

export const TENTS_DETAILS_REQUEST = "TENTS_DETAILS_REQUEST";
export const TENTS_DETAILS_SUCCESS = "TENTS_DETAILS_SUCCESS";
export const TENTS_DETAILS_FAIL = "TENTS_DETAILS_FAIL";

export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const GET_TENTS_A_REQUEST = "GET_TENTS_A_REQUEST";
export const GET_TENTS_A_SUCCESS = "GET_TENTS_A_SUCCESS";
export const GET_TENTS_A_FAIL = "GET_TENTS_A_FAIL";

export const NEW_TENTS_A_REQUEST = "NEW_TENTS_A_REQUEST";
export const NEW_TENTS_A_SUCCESS = "NEW_TENTS_A_SUCCESS";
export const NEW_TENTS_A_FAIL = "NEW_TENTS_A_FAIL";

export const DELETE_TENTS_A_REQUEST = "DELETE_TENTS_A_REQUEST";
export const DELETE_TENTS_A_SUCCESS = "DELETE_TENTS_A_SUCCESS";
export const DELETE_TENTS_A_FAIL = "DELETE_TENTS_A_FAIL";

export const UPDATE_TENTS_A_REQUEST = "UPDATE_TENTS_A_REQUEST";
export const UPDATE_TENTS_A_SUCCESS = "UPDATE_TENTS_A_SUCCESS";
export const UPDATE_TENTS_A_FAIL = "UPDATE_TENTS_A_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
