export const ALL_TENTS_SUCCESS = "ALL_TENTS_SUCCESS";
export const ALL_TENTS_FAIL = "ALL_TENTS_FAIL";

export const TENTS_DETAILS_SUCCESS = "TENTS_DETAILS_SUCCESS";
export const TENTS_DETAILS_FAIL = "TENTS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
