export const GET_USERS_A_REQUEST = "GET_USERS_A_REQUEST";
export const GET_USERS_A_SUCCESS = "GET_USERS_A_SUCCESS";
export const GET_USERS_A_FAIL = "GET_USERS_A_FAIL";

export const USER_DETAILS_A_REQUEST = "USER_DETAILS_A_REQUEST";
export const USER_DETAILS_A_SUCCESS = "USER_DETAILS_A_SUCCESS";
export const USER_DETAILS_A_FAIL = "USER_DETAILS_A_FAIL";

export const EDIT_USER_DETAILS_A_REQUEST = "EDIT_USER_DETAILS_A_REQUEST";
export const EDIT_USER_DETAILS_A_SUCCESS = "EDIT_USER_DETAILS_A_SUCCESS";
export const EDIT_USER_DETAILS_A_FAIL = "EDIT_USER_DETAILS_A_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL";

export const USER_ORDER_DETAILS_REQUEST = "USER_ORDER_DETAILS_REQUEST";
export const USER_ORDER_DETAILS_SUCCESS = "USER_ORDER_DETAILS_SUCCESS";
export const USER_ORDER_DETAILS_FAIL = "USER_ORDER_DETAILS_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
